### ISSUE TITLE
求教关于多用户的问题

### ISSUE THREAD

**Issue by vivagonna** [GaiZhenbiao/SynologyChatGPT#10]
不同用户之间是如何区分的，是只由不同的Openai API key来区分吗？
既然同一个群晖服务器上的用户创建newuser时都是使用同一个baseurl和botkey，是否可以用一个简化的的newuser命令设置默认baseurl和botkey？

**Comment by GaiZhenbiao** [comment]
根据群晖账户来区分。也许可以，但我暂时没有为这个repo添加新功能的计划

**Comment by vivagonna** [comment]
了解，感谢回复。我找到在哪里定义默认值了。
