### ISSUE TITLE
manage.py错误

### ISSUE THREAD

**Issue by ziwuchina** [GaiZhenbiao/SynologyChatGPT#2]
ash-4.3# sudo python manage.py makemigrations chat
  File "manage.py", line 17
    ) from exc
         ^
SyntaxError: invalid syntax
ash-4.3# sudo python manage.py migrate
  File "manage.py", line 17
    ) from exc
         ^
SyntaxError: invalid syntax
ash-4.3#

**Comment by GaiZhenbiao** [comment]
说明你用的是Python2。你应该试试：

```
sudo python3 manage.py makemigrations chat 
```
