### ISSUE TITLE
能在另一台内网的linux上搭建吗

### ISSUE THREAD

**Issue by airport666** [GaiZhenbiao/SynologyChatGPT#4]
能在另一台内网的linux上搭建吗，对接内网的群晖机器人，毕竟群晖装python3感觉头大，内网虚拟一台linux更轻松点

**Comment by GaiZhenbiao** [comment]
可以的。当然可以，填写正确的内网IP就行。不要再填127.0.0.1这个本地回环地址了。

**Comment by airport666** [comment]
<img width="484" alt="截屏2023-03-11 15 26 49" src="https://user-images.githubusercontent.com/112411280/224471310-fe32c68e-bd3b-4993-98f6-32adf3a92aa1.png">



<img width="546" alt="截屏2023-03-11 15 28 24" src="https://user-images.githubusercontent.com/112411280/224471378-1f1eebb9-8c84-4763-a10f-8a43d973a3cc.png">

我碰到一个错误，不知道错在哪里

**Comment by GaiZhenbiao** [comment]
请提供更详细的信息。你这样我也没法看出错误原因。

**Comment by airport666** [comment]
<img width="574" alt="截屏2023-03-11 16 14 12" src="https://user-images.githubusercontent.com/112411280/224473414-6b9a49df-3ab9-4d9f-a919-6fe241533953.png">



<img width="467" alt="截屏2023-03-11 16 14 22" src="https://user-images.githubusercontent.com/112411280/224473423-5bff5a6b-f7a3-492e-ab1f-11d96b3b37a6.png">



<img width="488" alt="截屏2023-03-11 16 14 41" src="https://user-images.githubusercontent.com/112411280/224473437-5e78682e-84b0-415c-945b-22a174b2fd40.png">



服务部署在10.10.10.13，裙晖地址在10.10.10.252，聊天界面用/newuser，服务端也会响应，但是是错误400

**Comment by GaiZhenbiao** [comment]
oh，这应该是ALLOWED_HOSTS设置有误，Django拒绝了不在白名单里的请求。
在本项目文件夹`SynologyChatGPT`下（注意和项目名重名），有一个settings.py。
<img width="546" alt="image" src="https://user-images.githubusercontent.com/51039745/224483322-e90cd7a1-a69e-420c-aa10-5f5d15b64b13.png">
在第28行这个列表中，加入群晖的内网IP`10.10.10.252`，成这样：

```
ALLOWED_HOSTS = ["10.10.10.252", "127.0.0.1"]
```

应该就可以解决400问题了。

**Comment by airport666** [comment]
<img width="675" alt="截屏2023-03-11 21 54 48" src="https://user-images.githubusercontent.com/112411280/224488720-e7ed4c09-82d3-46d8-a264-106f363a91b6.png">

<img width="456" alt="截屏2023-03-11 21 55 38" src="https://user-images.githubusercontent.com/112411280/224488734-f9004630-68fa-4593-b00b-e5df19975c73.png">

仍然报错400

**Comment by airport666** [comment]
<img width="993" alt="截屏2023-03-11 21 59 01" src="https://user-images.githubusercontent.com/112411280/224488911-8c70e76c-fb30-472f-ab50-afa678c6b3e9.png">

打开了debug，提示我还需要把服务端本级加入allowed hosts，试了一下，正常通讯了
<img width="648" alt="截屏2023-03-11 22 00 51" src="https://user-images.githubusercontent.com/112411280/224488971-6fe0b3c7-8ce3-4a3e-a1e4-9a7548b4d638.png">

**Comment by GaiZhenbiao** [comment]
原来是这样，那我关闭这个issue了
