### ISSUE TITLE
经常性的连接失败

### ISSUE THREAD

**Issue by rui12366B** [GaiZhenbiao/SynologyChatGPT#5]
收到了ID为4的用户的消息：你好
[12/Mar/2023 15:31:48] "POST / HTTP/1.1" 200 0
连接失败
发送的消息为：连接失败，请检查网络连接。
Performing system checks...

**Comment by GaiZhenbiao** [comment]
请提供更详细的描述

**Comment by rui12366B** [comment]
> 请提供更详细的描述

问题出现的原因是和openai的访问不稳定，可以加上自定义api.openai.com的功能或者加上http代理功能吗

**Comment by GaiZhenbiao** [comment]
已经有这个功能了。看下“高级”面板。
<img width="351" alt="image" src="https://user-images.githubusercontent.com/51039745/227722180-59867bcd-df79-44f0-bee7-bea73d86eaf7.png">

**Comment by rui12366B** [comment]
> 已经有这个功能了。看下“高级”面板。 <img alt="image" width="351" src="https://user-images.githubusercontent.com/51039745/227722180-59867bcd-df79-44f0-bee7-bea73d86eaf7.png">

好的，谢谢
