### ISSUE TITLE
一个奇怪的bug

### ISSUE THREAD

**Issue by vivagonna** [GaiZhenbiao/SynologyChatGPT#9]
当向chatgpt发送下面这条指令时，chatgpt能正确返回信息到后端，但是synology chat里面显示不出来，写其他代码则没有问题

`写一段python代码 计算100以内的质数`

**Comment by mujiannan** [comment]
我已经定位到了该问题，不仅是这段代码，而是所有包含“%”、“&”等特殊字符的回复都无法收到。  
原因是项目代码使用requests直接Post了json字符串，但群晖机器人实际接收*application/x-www-form-urlencoded*。

**Comment by mujiannan** [comment]
我已经修复了这个问题并提交了PR。  
我觉得群晖的Chat应用实在太烂了，功能难用不说，文档也匮乏。一个破机器人接口设计得极其奇葩且没有详细文档。  
另外，这个项目选择斜杠命令就是个错误，Synology Chat的手机端应用压根不支持斜杠命令。  

不，我觉得我们根本就不应该为Synology Chat开发任何应用，实在太恶心了。

**Comment by GaiZhenbiao** [comment]
我开发这个项目的时候也发现了这一点，群晖 Chat 的文档写得极差，很多东西得自己琢磨
